#!/usr/bin/env bash

# dash-to-panel
dconf write /org/gnome/shell/extensions/dash-to-panel/appicon-margin 8
dconf write /org/gnome/shell/extensions/dash-to-panel/appicon-padding 2
dconf write /org/gnome/shell/extensions/dash-to-panel/click-action "'CYCLE'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-1 "'#5294e2'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-2 "'#5294e2'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-3 "'#5294e2'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-4 "'#5294e2'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-dominant false
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-override true
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-unfocused-1 "'#5294e2'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-unfocused-2 "'#5294e2'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-unfocused-3 "'#5294e2'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-unfocused-4 "'#5294e2'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-color-unfocused-different false
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-position "'BOTTOM'"
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-size 2
dconf write /org/gnome/shell/extensions/dash-to-panel/dot-style-focused "'METRO'"
dconf write /org/gnome/shell/extensions/dash-to-panel/focus-highlight true
dconf write /org/gnome/shell/extensions/dash-to-panel/focus-highlight-color "'#eeeeee'"
dconf write /org/gnome/shell/extensions/dash-to-panel/group-apps true
dconf write /org/gnome/shell/extensions/dash-to-panel/group-apps-label-font-color "'#dddddd'"
dconf write /org/gnome/shell/extensions/dash-to-panel/group-apps-underline-unfocused true
dconf write /org/gnome/shell/extensions/dash-to-panel/group-apps-use-fixed-width true
dconf write /org/gnome/shell/extensions/dash-to-panel/group-apps-use-launchers false
dconf write /org/gnome/shell/extensions/dash-to-panel/hot-keys true
dconf write /org/gnome/shell/extensions/dash-to-panel/hotkeys-overlay-combo "'ALWAYS'"
dconf write /org/gnome/shell/extensions/dash-to-panel/isolate-monitors false
dconf write /org/gnome/shell/extensions/dash-to-panel/isolate-workspaces true
dconf write /org/gnome/shell/extensions/dash-to-panel/location-clock "'STATUSRIGHT'"
dconf write /org/gnome/shell/extensions/dash-to-panel/middle-click-action "'LAUNCH'"
dconf write /org/gnome/shell/extensions/dash-to-panel/multi-monitors true
dconf write /org/gnome/shell/extensions/dash-to-panel/panel-position "'BOTTOM'"
dconf write /org/gnome/shell/extensions/dash-to-panel/panel-size 40
dconf write /org/gnome/shell/extensions/dash-to-panel/primary-monitor -1
dconf write /org/gnome/shell/extensions/dash-to-panel/shift-click-action "'MINIMIZE'"
dconf write /org/gnome/shell/extensions/dash-to-panel/shift-middle-click-action "'LAUNCH'"
dconf write /org/gnome/shell/extensions/dash-to-panel/shortcut-previews false
dconf write /org/gnome/shell/extensions/dash-to-panel/show-activities-button false
dconf write /org/gnome/shell/extensions/dash-to-panel/show-appmenu false
dconf write /org/gnome/shell/extensions/dash-to-panel/show-apps-icon-file "['']"
dconf write /org/gnome/shell/extensions/dash-to-panel/show-favorites true
dconf write /org/gnome/shell/extensions/dash-to-panel/show-show-apps-button false
dconf write /org/gnome/shell/extensions/dash-to-panel/show-showdesktop-button true
dconf write /org/gnome/shell/extensions/dash-to-panel/show-tooltip false
dconf write /org/gnome/shell/extensions/dash-to-panel/stockgs-keep-dash false
dconf write /org/gnome/shell/extensions/dash-to-panel/stockgs-panelbtn-click-only false
dconf write /org/gnome/shell/extensions/dash-to-panel/taskbar-position "'LEFTPANEL_FLOATCENTER'"
