#!/usr/bin/env bash

# params
FOLDER=/tmp/mychromeinstance
URL="http://localhost:3000"

# remove previous created profiles
rm -rf $FOLDER || true

# open new chrome instance
google-chrome \
  --no-default-browser-check \
  --no-first-run \
  --disable-default-apps \
  --disable-popup-blocking \
  --disable-translate \
  --user-data-dir=$FOLDER \
  $URL
